"""Measure the workflow against ground truth the analysis never sees.

Run:  uv run python -m app.investigation.evaluate [--seeds 0 11 23 37 41] [--json out.json]

This is the only investigation module that reads a scenario's ground truth,
and nothing on the analysis path imports it. Each seed is a variant of
Operation Broken Mirror with the same structure and different names, numbers
and event times.

Measured per variant:
  asserted        connections a method reports as supported
  false asserted  of those, how many have no supported explanation that holds
                  up against ground truth
  misleading      supported connections whose first-listed explanation, the one
                  an investigator reads first, is unsound
  leads / false   connections raised for review instead of asserted, and how
                  many of those are false
  reviews         checks needed, in planner order and in random order, before no
                  false lead and no false assertion remains

An explanation is sound when some assignment of real people to its references
makes every hop hold: every statement it uses is true, every call or transfer
is attributed to the people who really used those numbers at that moment, every
identity hop joins references to one real person, and no one in the middle is a
benign high-activity contact.

Scope, printed with every result: synthetic scenarios generated by this
repository. This shows behaviour on those scenarios. It is not field accuracy,
and it does not measure investigative effectiveness.
"""

from __future__ import annotations

import argparse
import json
import random
import statistics
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from itertools import product
from pathlib import Path

from app.investigation import engine as E
from app.investigation import lineage, verification
from app.investigation.extract import extract
from app.investigation.normalize import case_of, identifier_key, name_of, name_tokens
from app.investigation.sensitivity import _with
from app.seed.broken_mirror import build_case_files, cast_for, ground_truth

IST = timezone(timedelta(hours=5, minutes=30))
SCOPE = (
    "Synthetic scenarios generated by this repository. Shows behaviour on those scenarios; "
    "not field accuracy, not investigative effectiveness."
)


def _day(text: str | None) -> datetime | None:
    return datetime.fromisoformat(text).replace(tzinfo=IST) if text else None


@dataclass
class Truth:
    refs: dict[tuple[str, str], str]
    users: dict[str, list[tuple[str, datetime | None, datetime | None]]]
    relations: set[frozenset[str]]
    hubs: set[str]
    false_files: set[str]

    @classmethod
    def load(cls, data: dict) -> Truth:
        refs = {
            (case, " ".join(name_tokens(name))): real
            for case, names in data["references"].items()
            for name, real in names.items()
        }
        users: dict[str, list] = {}
        for phone, spans in data["phone_users"].items():
            users[identifier_key("phone", phone)] = [(r, _day(s), _day(e)) for r, s, e in spans]
        for account, real in data["account_holders"].items():
            users[identifier_key("account", account)] = [(real, None, None)]
        return cls(
            refs=refs,
            users=users,
            relations={frozenset(pair) for pair in data["true_relations"]},
            hubs=set(data["benign_hubs"]),
            false_files=set(data["false_claim_files"]),
        )

    def real(self, person: str) -> set[str]:
        case, name = case_of(person), name_of(person)
        if case == "ALL":
            return {real for (_, n), real in self.refs.items() if n == name}
        found = self.refs.get((case, name))
        return {found} if found else set()

    def user(self, identifier: str, at: datetime) -> str | None:
        for real, start, end in self.users.get(identifier, []):
            if (start is None or at >= start) and (end is None or at < end):
                return real
        return None


@dataclass
class Variant:
    seed: int
    snapshot: E.Snapshot
    names: dict[str, str]
    truth: Truth
    subjects: list[str]


def load_variant(seed: int) -> Variant:
    cast = cast_for(seed)
    files = build_case_files(cast)
    assertions: list[E.Assertion] = []
    infos = {}
    names: dict[str, str] = {}
    for case, items in files.items():
        for item in items:
            out = extract(item.raw, case=case, kind=item.kind)
            assertions.extend(out.assertions)
            infos[(case, out.sha256)] = lineage.ArtifactInfo(
                out.sha256,
                case,
                item.filename,
                item.kind,
                out.reference,
                out.source_reference,
                out.document_date,
            )
            names[out.sha256] = item.filename
    assertions.sort(key=lambda a: a.key)
    snapshot = E.Snapshot(
        cases=tuple(sorted(files)),
        assertions=tuple(assertions),
        links=tuple(lineage.detect(assertions, infos)),
    )
    baseline = E.derive(snapshot)
    return Variant(seed, snapshot, names, Truth.load(ground_truth(cast)), sorted(baseline.anchors))


# --- Soundness ----------------------------------------------------------------------------------


class Judge:
    def __init__(self, variant: Variant, projection: E.Projection) -> None:
        self.variant = variant
        self.projection = projection
        self.by_key = variant.snapshot.assertion_map()

    def _true(self, a: E.Assertion) -> bool:
        return (
            a.kind != E.CLAIM
            or self.variant.names.get(a.artifact) not in self.variant.truth.false_files
        )

    def _derivation(
        self, edge: E.Edge, derivation: frozenset[str], source: str, target: str
    ) -> bool:
        atoms = [self.by_key[k] for k in derivation if k in self.by_key]
        if not all(self._true(a) for a in atoms):
            return False
        truth = self.variant.truth
        if edge.type in E.EVENT_EDGE_TYPES:
            event = next(a for a in atoms if a.predicate in (E.CONTACT, E.TRANSFER))
            return (
                truth.user(event.subject, event.start) == source
                and truth.user(event.object or "", event.start) == target
            )
        if edge.type == E.CLAIMED:
            return frozenset({source, target}) in truth.relations
        return source == target  # SAME_AS

    def _step(self, step: E.Step, assign: dict[str, str]) -> bool:
        for key in step.edges:
            edge = self.projection.edges.get(key)
            if edge is None:
                continue
            forward = edge.source == step.source
            source = assign[step.source] if forward else assign[step.target]
            target = assign[step.target] if forward else assign[step.source]
            if any(self._derivation(edge, d, source, target) for d in edge.derivations):
                return True
        return False

    def sound(self, explanation: E.Explanation) -> bool:
        truth = self.variant.truth
        options = [sorted(truth.real(node)) for node in explanation.nodes]
        if any(not choices for choices in options):
            return False
        for combo in product(*options):
            assign = dict(zip(explanation.nodes, combo, strict=True))
            if any(assign[n] in truth.hubs for n in explanation.nodes[1:-1]):
                continue
            if all(self._step(step, assign) for step in explanation.steps):
                return True
        return False


def score_projection(variant: Variant, projection: E.Projection) -> dict:
    judge = Judge(variant, projection)
    findings = list(projection.findings.values())
    supported = [f for f in findings if f.status == E.SUPPORTED]
    leads = [f for f in findings if f.status == E.LEAD]
    return {
        "asserted": len(supported),
        "false_asserted": sum(
            not any(x.status == E.SUPPORTED and judge.sound(x) for x in f.explanations)
            for f in supported
        ),
        "misleading_first": sum(not judge.sound(f.explanations[0]) for f in supported),
        "leads": len(leads),
        "false_leads": sum(not any(judge.sound(x) for x in f.explanations) for f in leads),
    }


# --- Review ------------------------------------------------------------------------------------


def _truthful(task: verification.Task, projection: E.Projection, variant: Variant) -> dict:
    """The outcome a careful reviewer with access to the real records would record."""
    truth = variant.truth
    if task.kind == "attribution":
        conflicts = [
            c for c in projection.conflicts if set(h for _, h in c.holders) & set(task.evidence)
        ]
        if conflicts:
            first = conflicts[0]
            actual = truth.user(first.identifier, first.at)
            for outcome in task.outcomes:
                if outcome.key.startswith("holder:") and actual in truth.real(outcome.key[7:]):
                    return outcome.overrides
        return {}
    if task.kind == "identity":
        candidate = projection.candidates[task.targets[0]]
        same = bool(truth.real(candidate.a) & truth.real(candidate.b))
        return {"identity": {candidate.key: "accepted" if same else "rejected"}}
    # Proposed copies in these scenarios really are copies; records are accurate.
    return {}


class Reviewer:
    """Replays reviews, remembering every state it has already computed."""

    def __init__(self, variant: Variant) -> None:
        self.variant = variant
        self.cache: dict[str, tuple[E.Projection, list[verification.Task], dict]] = {}

    def state(self, scenario: E.Scenario):
        key = scenario.canonical()
        if key not in self.cache:
            projection = E.derive(self.variant.snapshot, scenario, subjects=self.variant.subjects)
            tasks = verification.plan(
                self.variant.snapshot, projection, self.variant.names, limit=50
            )
            self.cache[key] = (projection, tasks, score_projection(self.variant, projection))
        return self.cache[key]

    def reviews_needed(self, pick, limit: int = 10) -> int | None:
        scenario = E.BASELINE
        done: set[str] = set()
        for count in range(limit + 1):
            projection, tasks, score = self.state(scenario)
            if score["false_leads"] == 0 and score["false_asserted"] == 0:
                return count
            open_tasks = [t for t in tasks if t.key not in done]
            if not open_tasks:
                return None
            task = pick(open_tasks)
            done.add(task.key)
            overrides = _truthful(task, projection, self.variant)
            if overrides:
                scenario = _with(scenario, **overrides)
        return None


def evaluate_variant(variant: Variant, random_orders: int = 12) -> dict:
    naive = E.derive(variant.snapshot, E.Scenario.build(naive=True))
    baseline = E.derive(variant.snapshot, subjects=variant.subjects)
    reviewer = Reviewer(variant)
    planned = reviewer.reviews_needed(lambda tasks: tasks[0])
    rng = random.Random(variant.seed)
    shuffled = [
        reviewer.reviews_needed(lambda tasks: rng.choice(tasks)) for _ in range(random_orders)
    ]
    finished = [n for n in shuffled if n is not None]
    return {
        "seed": variant.seed,
        "naive": score_projection(variant, naive),
        "netintel": score_projection(variant, baseline),
        "reviews": {
            "planner": planned,
            "random_mean": round(statistics.mean(finished), 2) if finished else None,
            "random_worst": max(finished) if finished else None,
            "random_unfinished": len(shuffled) - len(finished),
            "random_orders": random_orders,
        },
    }


def run(seeds: list[int]) -> dict:
    results = [evaluate_variant(load_variant(seed)) for seed in seeds]
    totals = {}
    for method in ("naive", "netintel"):
        totals[method] = {
            metric: sum(r[method][metric] for r in results) for metric in results[0][method]
        }
    return {"scope": SCOPE, "seeds": seeds, "variants": results, "totals": totals}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Evaluate NetIntel on synthetic ground truth.")
    parser.add_argument("--seeds", type=int, nargs="+", default=[0, 11, 23, 37, 41])
    parser.add_argument("--json", type=Path)
    args = parser.parse_args(argv)

    report = run(args.seeds)
    header = f"{'seed':>5} | {'method':9} | asserted | false | misleading 1st | leads | false leads"
    print(header)
    print("-" * len(header))
    for variant in report["variants"]:
        for method in ("naive", "netintel"):
            s = variant[method]
            print(
                f"{variant['seed']:>5} | {method:9} | {s['asserted']:>8} | "
                f"{s['false_asserted']:>5} | {s['misleading_first']:>14} | "
                f"{s['leads']:>5} | {s['false_leads']:>11}"
            )
        r = variant["reviews"]
        print(
            f"      reviews until no false lead or assertion: planner {r['planner']}, random mean "
            f"{r['random_mean']} (worst {r['random_worst']}, {r['random_orders']} orders)"
        )
    print(f"\nTotals: {json.dumps(report['totals'])}")
    print(f"Scope: {SCOPE}")
    if args.json:
        args.json.write_text(json.dumps(report, indent=2), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
